---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: copy file from server to node
      copy:
        src: /home/ansadmin/index.html
        dest: /home/ansadmin
        mode: 0600
        owner: rohit
        group: rohit
