---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: installing packages
      yum:
        name: httpd
        state: installed

    - name: starting the services
      service:
        name: httpd
        state: started
